src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @UniqueEntity(fields={"pseudo"}, message="There is already an account with this pseudo")
 */
class Client implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="client", orphanRemoval=true)
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER'; 

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(?string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setClient($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getClient() === $this) {
                $commande->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_enregistrement;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=Detail::class, mappedBy="commande", orphanRemoval=true)
     */
    private $details;

    public function __construct()
    {
        $this->details = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection<int, Detail>
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(Detail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details[] = $detail;
            $detail->setCommande($this);
        }

        return $this;
    }

    public function removeDetail(Detail $detail): self
    {
        if ($this->details->removeElement($detail)) {
            // set the owning side to null (unless already changed)
            if ($detail->getCommande() === $this) {
                $detail->setCommande(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/profil")
 */
class ProfilController extends AbstractController
{
    /**
     * @Route("/", name="app_profil")
     */
    public function index(): Response
    {
        /**
            Pour récupérer les informtions de l'utilisateur connecté dans le contrôleur :
                $client = $this->getUser();
            Mais on peut récupérer l'utilisateur connecté directement dans un fichier Twig avec :
                app.user
        */
        return $this->render('profil/index.html.twig');
    }

    /**
     * EXO : ajouter une route dans ce contrôleur pour afficher la liste des produits
     *       dans une liste UL (pour chaque produit afficher le titre et le prix)
     */

    /**
     * @Route("/liste-produits", name="app_profil_liste")
     */
    public function liste(ProduitRepository $produitRepository): Response
    {
        return $this->render("profil/liste_produits.html.twig", [ 
            "produits" => $produitRepository->findAll() 
        ]);
    }

    /**
     * @route("/detail-commande-{id}", name="app_profil_commande", requirements={"id"="\d+"})
    */
    public function detailCommande(Commande $commande): Response{
        if( $commande->getClient() == $this->getUser()){
                   return $this->render("profil/detail_commande.html.twig", [
            "commande" => $commande
        ]); 
        }
        throw $this->createAccessDeniedException("Vous n'avez pas accès à cet URL");
        // $this->addFlash("danger", "ERREUR 403 : Vous n'avez pas acces a cet URL");
        // return $this->redirectToRoute("app_home");
    }

}

templates/profil/detail_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil | Détail de la commande{% endblock %}

{% block h1 %}Détail de ma commande n° {{ commande.id }} {% endblock %}

{% block body %}


    <table class="table">
        <tbody>
            <tr>
            <th>Numero de commande</th>
            <td>{{ commande.id }}</td>
            </tr>

            <tr>
                <th>Date</th>
                <td>{{ commande.dateEnregistrement ? 'Le ' ~ commande.dateEnregistrement|date('d/m/Y à H:i:s') : '' }}</td>
            </tr>

            <tr>
                <th>Etat</th>
                <td>{{ commande.etat }}</td>
            </tr>

            <tr>
                <th>Détail de la commande</th>
                <td>
                <table class="table table-bordered">
            <thead class="thead-dark">
        <tr>
            <th>Identifiant</th>
            <th>Désignation</th>
            <th>Qté</th>
            <th>Sous-total</th>
        </tr>
        </thead>
        <tbody>
        {% for detail in commande.details %}
            <tr>
                <td> {{ detail.produit.id }} </td>
                <td> {{ detail.produit.titre }} </td>
                <td> {{ detail.quantite }} </td>
                <td> {{ detail.quantite * detail.prix }} €</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr class="thead-dark">
            <th colspan="3">MONTANT</th>
            <td><strong>{{commande.montant}} €</strong></td>
            </tr>
        </tfoot>
            </table>
                </td>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Profil Client{% endblock %}

{% block h1 %}Profil client{% endblock %}

{% block body %}
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Pseudo : </strong>{{ app.user.pseudo }}
        </li>
        <li class="list-group-item">
            <strong>Identité : </strong>{{ app.user.prenom ~ " " ~ app.user.nom }}
        </li>
        <li class="list-group-item">
            <strong>Adresse : </strong>{{ app.user.adresse ~ " " ~ app.user.codePostal ~ " " ~ app.user.ville }}
        </li>

        <li class="list-group-item">
            <strong>E-mail : </strong>{{ app.user.email }}
        </li>

        <li class="list-group-item">
            <strong>Type : </strong>
                {% for role in app.user.roles %}
                    {% if role == "ROLE_ADMIN" %}
                        Administrateur
                    {% elseif role == "ROLE_CLIENT" %}
                        Client
                    {% elseif role == "ROLE_MODO" %}
                        Modérateur
                    {% endif %}
                {% endfor %}

                {# Afficher les rôles de l'utilisateur en remplaçant
                    ROLE_ADMIN par Administrateur
                    ROLE_CLIENT par Client
                    ROLE_MODO par Modérateur
                #}
        </li>

        <li class="list-group-item">
            <strong>Mes commandes : </strong>
            <table class="table">
                <thead>
                    <tr>
                        <th>Numéro</th>
                        <th>Date</th>
                        <th>Montant</th>
                        <th>État</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cmd in app.user.commandes %}
                        <tr>
                            <td> <a href="{{ path('app_profil_commande', {id: cmd.id}) }}" class="btn btn-primary" title="Voir le détail de la commande"> {{ cmd.id }} </a></td>
                            <td>{{ cmd.dateEnregistrement|date("d/m/y") }}</td>
                            <td>{{ cmd.montant }} €</td>
                            <td>{{ cmd.etat|upper }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="3">Aucune commande</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </li>

    </ul>
{% endblock %}

templates/profil/liste_produits.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <ul class="list-group">
        {% for produit in produits %}
            <li class="list-group-item">
                {{ produit.titre }} - {{ produit.prix }}€
            </li> 
        {% endfor %}
    </ul>
{% endblock %}

{% block h1 %}Liste des produits{% endblock %}